export enum UserRoutes {
  HOME = '/',
  SERVICES = '/services',
  PARKING_LOTS = '/parking-lots',
  ADD_CREDITS = '/add-credits',
  PROFILE = '/profile',
  CHECK_AMOUNT = '/check-amount',
  MY_PLATES = '/check-amount/my-plates',
  PARKING_HISTORY = '/parking-history',
  CHARGING_HISTORY = '/energy-history',
  CONTACTS = '/contacts',
  TERMS = '/terms',
  AUTHENTICATION = '/authentication',
  LOTS = '/lots',
  FORGOT_PASSWORD = '/forgot-password',
  SUCCESS = 'payment/success',
  REPORT = '/report',
  MESSAGE_RECEIVED = '/message-received',
  DELETE = 'profile/delete',
  REQUEST_SENT = '/request-sent',
  CHARGING = '/charging',
  CHARGING_POINT = '/charging/charging-point',
  START_CHARGING = '/start-charging',
  STOP_CHARGING = '/start-charging/stop-charging',
  COMPLETED_CHARGING = '/completed-charging'
}

export enum ApiRoutes {
  FORGOT_PASSWORD = '/api/users/send-password-recovery-link',
  CHECK_IS_RECOVERY_CODE_VALID = '/api/users/check-is-recovery-code-valid',
  CHANGE_PASSWORD_BY_RECOVERY_CODE = '/api/users/change-password-by-recovey-code',
  CHANGE_PASSWORD = '/api/users/change-password',
  REGISTER = '/api/auth/singup',
  USERS = '/api/users',
  LOGIN = '/api/auth/mobile-login',
  PARKING_LOTS = '/api/parking-lots',
  PAYMENT_ADD_TOKENS = '/api/checkout/payment-request/kevin/add-tokens',
  CALCULATE_BY_PLATE = '/api/checkout/calculate',
  SMS_LOG = '/api/checkout/log/sms',
  PAYMENT_REQUEST_TO_KEVIN = '/api/checkout/payment-request/kevin',
  PAY_WITH_CREDITS = '/api/checkout/pay-with-tokens',
  PAY_WITH_DISCOUNT_CODE = '/api/checkout/pay-with-discount',
  ISSUE_REPORT = '/api/issue-report',
  TICKETS = '/api/tickets',
  CHARGINGS = '/api/chargings',
  // INBALANCE API
  INBALANCE_ACCESS_TOKEN = '/access-token',
  INBALANCE_LOTS = '/cluster/changes/2022-08-08T08%3A08%3A00%2B08%3A00',
  INBALANCE_CLUSTER = '/cluster',
  INBALANCE_CLUSTERS = '/cluster/map',
  INBALANCE_START_CHARGING = '/charging/start',
  INBALANCE_STOP_CHARGING = '/charging/stop',
  INBALANCE_CHECK_SESSION = '/charging/session',
}